import Header from '@/app/_components/Header'
import { inter, interTight } from './fonts'
import '@/app/_styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{
        "--font-inter": inter.style.fontFamily,
        "--font-inter-tight": interTight.style.fontFamily,
      }}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
