import Header from '@/app/_components/Header'
import '@/app/_styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel='preload'
          href='/fonts/Inter-VariableFont_opsz,wght.woff2'
          as='font'
          type='font/woff2'
          crossOrigin='anonymous'
        />
        <link
          rel='preload'
          href='/fonts/InterTight-VariableFont_wght.woff2'
          as='font'
          type='font/woff2'
          crossOrigin='anonymous'
        />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
